post_install() {
	echo " >> initramfs-scencrypt - READ ME!"
	echo " >> Make sure to add your encrypted disks to /etc/crypttab. There is"
	echo " >> no support for cryptdevice=... on the kernel command line."
	echo ""
	echo " >> Key file path must end in .gpg and the private key must be"
	echo " >> accessible by root."
	echo ""
	echo " >> For more information, read /usr/share/doc/initramfs-scencrypt/README.md"
}
